version: '3'
services:
  customer_db:
    profiles:
      - "local"
    platform: linux/x86_64
    container_name: customer_database
    image: mysql:8.0.23
#    restart: always
    environment:
      MYSQL_DATABASE: customer
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "${ORDER_DB_PORT:-3312}:3306"
    volumes:
      - ./src/main/resources/db/customer/customer.sql:/docker-entrypoint-initdb.d/init_db.sql

  restaurant_db:
    profiles:
      - "local"
    platform: linux/x86_64
    container_name: restaurant_database
    image: postgres:16.1
#    restart: always
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "${RESTAURANT_DB_PORT:-3313}:5432"
    volumes:
      - ./src/main/resources/db/restaurant/restaurant.sql:/docker-entrypoint-initdb.d/init_db.sql

  review_db:
#    profiles:
#      - "local"
    image: mongo:4.4.26-focal
#    restart: always
    platform: linux/x86_64
    container_name: review_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: review
    ports:
      - "${RESTAURANT_DB_PORT:-3314}:27017"
    volumes:
      - ./src/main/resources/db/review/review.js:/docker-entrypoint-initdb.d/init-mongo.js
