###

GET http://localhost:9191/api/customer
Accept: application/json

###

GET http://localhost:9191/api/restaurant
Accept: application/json

###

GET http://localhost:9191/api/review
Accept: application/json
